Task13 (Streams, lambda)
borkowsky/homework pull request #14
Opened 2024-11-25 17:11 UTC by borkowsky

2024-11-28 08:15 UTC, PavelIvanouski requested changes

2024-11-28 08:15 UTC, PavelIvanouski commented on src/by/it_academy/homework/task13/Main.java
> +                .limit(initialList.size() - 1)
initialList.size() = 8, .limit(initialList.size() - 1) = 7
после фильтрации по str -> !str.contains("3") останется 6

2024-11-28 08:15 UTC, PavelIvanouski commented on src/by/it_academy/homework/task13/Book.java
> +    private final String NAME;
апперкейсом обычно константы которые не изменяются и в коде используются. поля не обязательно

2024-11-28 08:15 UTC, PavelIvanouski commented on src/by/it_academy/homework/task13/BookManager.java
> +        return books.stream().filter(predicate).collect(Collectors.toList());
обычно стрим переносят по строкам (даже если return и в одну строку)
return books.stream()
                       .filter(predicate)
                       .collect(Collectors.toList());

2024-11-29 07:40 UTC, PavelIvanouski approved these changes

2024-11-29 07:40 UTC, PavelIvanouski commented on src/by/it_academy/homework/task13/Main.java
> +                .limit(initialList.stream()
как вариант тут еще раз отсортировать в обратном порядке и скипнуть 1

2024-11-30 18:36 UTC, borkowsky commented on src/by/it_academy/homework/task13/Main.java
> +                .limit(initialList.stream()
Кстати отличная идея🤔

2024-11-30 18:37 UTC, merged