Task 8 (Money and Airlines classes)
borkowsky/homework pull request #9
Opened 2024-10-14 18:46 UTC by borkowsky

2024-10-15 07:29 UTC, PavelIvanouski approved these changes

2024-10-15 07:29 UTC, PavelIvanouski commented on src/by/it_academy/homework/task8/money/Money.java
> +        injectCents(convertToCents() + convertToCents(dollars, cents));
возможно достаточно одного метода convertToCents(int dollars, int cents)
и тут вызывать convertToCents(this.dollars, this.cents) + convertToCents(dollars, cents)

2024-10-15 07:29 UTC, PavelIvanouski commented on src/by/it_academy/homework/task8/money/Money.java
> +                new String[]{"доллар", "доллара", "долларов"} :
список вараинтов слов можно вынести в поле класса
private static final String[] dollarLabels = new String[]{"доллар", "доллара", "долларов"} ;

2024-10-15 07:29 UTC, PavelIvanouski commented on src/by/it_academy/homework/task8/airlines/vehicles/Vehicle.java
> +public abstract class Vehicle {
разве vehicle это не транспортное средство?)

2024-10-15 07:29 UTC, PavelIvanouski commented on src/by/it_academy/homework/task8/airlines/Airlines.java
> +    private int helicopterCount;
не обязательно хранить в отдельных полях, тогда придется все время не забывать пересчитывать когда какие-то изменения в списке vehiclesList, проще по этому списку определять где нужно plainsCount, helicopterCount, quadcopterCount

2024-10-15 07:29 UTC, PavelIvanouski commented on src/by/it_academy/homework/task8/airlines/Airlines.java
> +                "из них " + plainsCount + " " + Utils.declOfNum(plainsCount, new String[]{
хороший подход - в Utils.declOfNum передавать массив возможных вариантов слов

2024-10-15 07:37 UTC, borkowsky commented on src/by/it_academy/homework/task8/airlines/vehicles/Vehicle.java
> +public abstract class Vehicle {
Ну это же по сути транспорт )

2024-10-15 07:38 UTC, borkowsky commented on src/by/it_academy/homework/task8/airlines/Airlines.java
> +    private int helicopterCount;
Я сделал это на случай если понадобится вывести в нескольких методах, и чтобы каждый раз не считать, сразу завести переменные. Привычка)

2024-10-15 07:39 UTC, borkowsky commented on src/by/it_academy/homework/task8/money/Money.java
> +                new String[]{"доллар", "доллара", "долларов"} :
Здесь тоже сделал для вывода данных с локализацией. Согласен, в данном примере необязательно.

2024-10-15 07:41 UTC, borkowsky commented on src/by/it_academy/homework/task8/money/Money.java
> +        injectCents(convertToCents() + convertToCents(dollars, cents));
Да, сделал избыточно. Писал методы заранее, а не по необходимости.

2024-10-16 12:02 UTC, PavelIvanouski requested changes

2024-10-16 12:02 UTC, PavelIvanouski commented on src/by/it_academy/homework/task8/airlines/Airlines.java
> +        return resultIdx;
тут может объект вернуть?
причем может же несколько подойти под диапазон

2024-10-17 06:56 UTC, PavelIvanouski approved these changes

2024-10-17 07:10 UTC, merged